# Generated by Django 4.1.10 on 2023-07-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site', models.CharField(max_length=100)),
            ],
        ),
    ]
