# Generated by Django 4.1.10 on 2023-07-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('idProd', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('image1', models.URLField()),
                ('prix1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site1', models.CharField(max_length=100)),
                ('image2', models.URLField()),
                ('prix2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site2', models.CharField(max_length=100)),
            ],
        ),
    ]
