# Generated by Django 4.1.7 on 2023-07-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('image1', models.URLField()),
                ('prix1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site1', models.CharField(max_length=100)),
                ('image2', models.URLField()),
                ('prix2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site2', models.CharField(max_length=100)),
            ],
        ),
    ]
