# Generated by Django 4.1.7 on 2023-07-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteScrappingApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
