# Generated by Django 4.1.10 on 2023-07-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteScrappingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='brand',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
